Add device bulk upload CSV template
d-rec/drec-origin pull request #429
Opened 2024-10-11 09:21 UTC by divinecharlotte

### Objective
Define a CSV format that can be used for bulk device creation

### Description
- Define fields names and which values to expect from the CSV template
- Create the CSV template

### Acceptance Criteria
- A CSV template which has all the fields needed for device creation
- At least 2 sample device data are added to the template to show which values to expect

2024-10-15 10:36 UTC, Kingcedru reviewed
**Suggestion:** Add more values in the columns for easy testing.

2024-10-15 10:36 UTC, Kingcedru submitted a review, later dismissed

2024-10-21 10:16 UTC, musayann requested changes

2024-10-21 10:16 UTC, musayann commented on integrators-scripts/integrator-daily-csv/device-bulk-upload-template.csv
> +2,Device002,Project B,456 Elm St,40.7128,-74.006,CAN,ES100,TC120,15,2023-02-01T00:00:00.000Z,,,,,,,,
can we move this outside this folder. I would like to have a folder called templates which would make it easy to find such templates.

can you create a folder called templates with this path `/apps/drec-api/templates`

2024-10-21 10:16 UTC, musayann commented on integrators-scripts/integrator-daily-csv/device-bulk-upload-template.csv
> +2,Device002,Project B,456 Elm St,40.7128,-74.006,CAN,ES100,TC120,15,2023-02-01T00:00:00.000Z,,,,,,,,
Then move this template into that folder

2024-10-22 08:07 UTC, musayann approved these changes

2024-10-22 08:07 UTC, merged