Remove rush in Dockerfile
d-rec/drec-origin pull request #430
Opened 2024-10-17 13:27 UTC by kunda4

Objective
Remove rush Command in the Dockerfile

2024-10-17 16:09 UTC, musayann requested changes

2024-10-17 16:09 UTC, musayann commented on apps/drec-api/Dockerfile
>  RUN npm i -g pnpm@9
do we need this pnpm here ?

2024-10-17 16:09 UTC, musayann commented on apps/drec-api/Dockerfile
> -RUN rush deploy -p @energyweb/origin-drec-api -t ./deployment --overwrite
Are you sure the remove of this step won't cause any harm?

2024-10-17 16:32 UTC, kunda4 commented on apps/drec-api/Dockerfile
>  RUN npm i -g pnpm@9
Yes, it is necessary because, during the build phase, it is used to run `pnpm build:ts`.

2024-10-23 08:29 UTC, musayann requested changes

2024-10-23 08:29 UTC, musayann commented on apps/drec-api/package.json
> +    "build": "npm run build:ts",
can you replace 
`npm` with `$npm_execpath`. To make the script agnostic of different package managers

2024-11-01 08:16 UTC, musayann requested changes

2024-11-01 08:16 UTC, musayann commented on apps/drec-api/Dockerfile
>  WORKDIR /dist/src/app
rename this to `/app`

2024-11-01 08:16 UTC, musayann commented on apps/drec-api/Dockerfile
>  WORKDIR /dist/src/app/apps/drec-api
this is no longer need

2024-11-01 08:16 UTC, musayann commented on apps/drec-api/Dockerfile
> +RUN npm i swagger-ui-express
I don't think we need this

2024-11-01 08:16 UTC, musayann commented on apps/drec-api/Dockerfile
> +CMD ["/bin/bash", "-c", "/dist/src/app/apps/drec-api"]
This command needs to be updated

2024-11-01 08:17 UTC, musayann commented
Fix the build pipeline

2024-11-04 08:10 UTC, musayann requested changes

2024-11-04 08:10 UTC, musayann commented on apps/drec-api/Dockerfile
> +RUN npm cache clean --force
I don't think we need this command

2024-11-04 13:00 UTC, musayann approved these changes

2024-11-04 13:00 UTC, merged