Feat: Storing failed meter reads
d-rec/drec-origin pull request #432
Opened 2024-10-17 19:43 UTC by Kingcedru

### Objective
To create a Model for the influx db that will store the Meter Reads for the failed analytics and store them

### Description
- Review if the Influx db model do already exist
- If not setup a reusable structure which would allow us to have multiple influx db models
- Store failed meter reads into the db

### Acceptance Criteria
- [x]  The influx db model that stores the failed meter reads
- [x] The influx db model can be reused in multiple places
- [x] The failed meter reads are stored in the db

2024-10-18 13:06 UTC, musayann requested changes

2024-10-18 13:06 UTC, musayann commented on apps/drec-api/src/pods/reads/influx-dbservice.service.ts
> +    this.client = new InfluxDB({
can we create a lib file that will be used in the whole project to read and write to influx db

Create a file in `/src/lib/influx-db.ts`

```ts
import { InfluxDB, Point } from '@influxdata/influxdb-client';

const dbConfig = {
  url: process.env.INFLUXDB_URL,
  token: process.env.INFLUXDB_TOKEN,
};

const dbWriter = () => {
  return new InfluxDB(dbConfig).getWriteApi(process.env.INFLUXDB_ORG || "", process.env.INFLUXDB_BUCKET);
};

const dbReader = () => {
  return new InfluxDB(dbConfig).getQueryApi(process.env.INFLUXDB_ORG || "");
};

const writePoints = async (points: Point[]) => {
  const writer = dbWriter();
  writer.writePoints(points);
  await writer.close();
};

const executeQuery = async (query: string) => {
  const reader = dbReader();
  const results = await reader.collectRows(query);
  return results;
};

export { dbReader, dbWriter, writePoints, executeQuery };
```

2024-10-18 13:06 UTC, musayann commented on apps/drec-api/src/pods/reads/influx-dbservice.service.ts
> +    );
This file wouldn't be needed any more. We would just create the points and then pass them to the `writePoints` function

2024-10-18 13:06 UTC, musayann commented on apps/drec-api/src/pods/reads/influx-dbservice.service.ts
> +      .stringField('read', read);
this should be an int field with measurement conversion and add the timestamp as it's done here https://github.com/energywebfoundation/energy-api/blob/efad87ee433f39523effb158987f4d230b847e96/packages/energy-api-influxdb/src/reads/reads.service.ts#L58

2024-11-01 07:59 UTC, musayann requested changes

2024-11-01 07:59 UTC, musayann commented on apps/drec-api/src/pods/reads/reads.service.ts
> +    const points: Point[] = [
can we multiply the read with the unit  as done here https://github.com/energywebfoundation/energy-api/blob/efad87ee433f39523effb158987f4d230b847e96/packages/energy-api-influxdb/src/reads/reads.service.ts#L59

2024-11-04 14:46 UTC, musayann requested changes

2024-11-04 14:46 UTC, musayann commented on apps/drec-api/src/pods/reads/reads.service.ts
> +  private getMultiplier(unit: Unit) {
Let's move this behavior into a helper file to help us convert into units

2024-11-04 14:46 UTC, musayann commented on apps/drec-api/src/pods/reads/reads.service.ts
> +  private getMultiplier(unit: Unit) {
the function would help us convert to `Wh`

2024-11-05 08:11 UTC, musayann requested changes

2024-11-05 08:11 UTC, musayann commented on apps/drec-api/src/pods/reads/reads.service.ts
> +  private getMultiplier(unit: Unit) {
The helper function would receive 2 parameters one for the amount(measurement) and the unit. And it would convert them to `Wh`

2024-11-06 12:34 UTC, Kingcedru commented
The function I create receives one parameter unit because if I use two parameters the function will only be used when storingFailedReads method yet there are other places we are converting to different units.
I decided to use the `NewroundMeasurementsToUnit` method because it is used when recording new reads and it returns the unit with a `Wh` value. This means each read value in the project must be converted to 'Wh' even if it was submitted in a different unit.

2024-11-07 14:45 UTC, musayann requested changes

2024-11-07 14:45 UTC, musayann commented on apps/drec-api/src/utils/convert-to-units.ts
> +    switch (unit) {
This function is not converting. It's just getting the conversion. Can you create a function that does the conversion?

It takes the measurement and unit as a parameter and returns the converted amount

2024-11-12 13:13 UTC, musayann approved these changes

2024-11-12 13:13 UTC, merged