feat: add contribution guidelines
d-rec/drec-origin pull request #439
Opened 2024-10-22 16:16 UTC by musayann

### Describe your changes

This PR adds a pull request template and a CONTRIBUTING.md file, which outline the guidelines for contributing to this project.

### Issue ticket number and link

- #405 

### Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] No existing features have been broken without good reason.
- [x] The code style guideline have been followed
- [x] Documentation has been updated to reflect your changes.

2024-10-22 17:49 UTC, Kingcedru approved these changes, later dismissed
Cleary and understandable

2024-10-23 07:28 UTC, divinecharlotte requested changes
One comment left

2024-10-23 07:28 UTC, divinecharlotte commented on CONTRIBUTING.md
> +    - Use lowercase letters and separate words with a hyphen
- I think this is kinda confusing this `kebab_case` is in snake_case yet the example provided is in the kebab-case. Perhaps updating the text to use the correct terms consistently will make it easier to follow. Just a small adjustment could make it perfectly clear!

2024-10-23 08:22 UTC, dmohns reviewed
Looks good to me. Few comments

2024-10-23 08:22 UTC, dmohns commented on CONTRIBUTING.md
> +## Documentation
Could we add a small section here regarding User Facing documentation as well? I.e. when new features are added, the User Facing documentation should be added at the same time.
(I know we currently don't have a good User Facing documentation, but would be nice to already agree in this procedure for the future)

2024-10-23 08:22 UTC, dmohns commented on CONTRIBUTING.md
> +- Do not use git force push
I find this statement a bit to generic. Sometimes it can be helpful the rewrite history. For example rebase-ing branches vs merging main. 
It's true, that we should almost never force push, however `push --force-with-lease` provides a security layer to prevent real bad things from happening and gives us access to rewriting history features.

2024-10-23 08:22 UTC, dmohns commented on CONTRIBUTING.md
> +- **Create Logically Consistent Commits:** Try to make mid-sized commits every few minutes or hours. However, the key is to ensure that each commit represents a logically consistent contribution. If
I find this a bit unrealistic and contradicting with what is mentioned later in the guide regarding squashes. If developers create a first PR they will receive Code reviews and change requests. Where do these changes go? Into a new commit every time? Then the individual commits are no longer logically consistent. Should developers squash the changes into their commits? It's disencouraged later in the guide.

There are two common ways to tackle this problem.

**Option 1:** It's developers responsibility to create logically consistent **commits** on their feature branches. This requires squashing. Pull Requests will be merged using the "Merge" option.

**Option 2:** (My personal preference) Squash-and-Merge. Developers can create many, potentially small commits on their feature branches. Pull Requests will be merged using the "Squash-and-Merge" option. It's developers responsibility to create logically consistent **Pull Requests**

2024-11-04 12:31 UTC, musayann commented on CONTRIBUTING.md
> +    - Use lowercase letters and separate words with a hyphen
Fixed

2024-11-04 12:31 UTC, musayann commented on CONTRIBUTING.md
> +## Documentation
I have added it

2024-11-04 12:32 UTC, musayann commented on CONTRIBUTING.md
> +- **Create Logically Consistent Commits:** Try to make mid-sized commits every few minutes or hours. However, the key is to ensure that each commit represents a logically consistent contribution. If
I have changed it to Consistent Pull Requests

2024-11-04 12:33 UTC, musayann commented on CONTRIBUTING.md
> +- Do not use git force push
I removed this statement all together. We can just enforce it using git rules

2024-11-04 14:28 UTC, dmohns approved these changes
Thanks 🙏

2024-11-05 06:56 UTC, merged