Ft/add bulk meter api
d-rec/drec-origin pull request #441
Opened 2024-10-28 07:28 UTC by Kingcedru

### Description

### Issue ticket number and link

- #425

### Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] No existing features have been broken without good reason.
- [ ] The code style guideline have been followed
- [ ] Documentation has been updated to reflect your changes.

2024-10-29 06:44 UTC, divinecharlotte requested changes
Hello @Kingcedru ,
I left a comment on this PR kindly check on it and please consider including all testing resources required in this PR to make the review process smooth

for this point 
`
Every record in the csv should go the validation and the same creation process as the entries which are submit to the /reads endpoint` I don't see where its implemented

2024-10-29 06:44 UTC, divinecharlotte commented on apps/drec-api/src/pods/reads/reads.service.ts
> -  }
- Why did you delete this ?? it was there to check on a single device upload, now when I try to add a device with an external ID that doesn't exist it won't catch that error. please consider checking on this and let's have it back as it's needed.

2024-11-11 08:06 UTC, musayann requested changes

2024-11-11 08:06 UTC, musayann commented on apps/drec-api/src/pods/reads/reads.processor.ts
> +  @Process('process-meter-reads')
can you rename this to `meter-reads-csv`

2024-11-11 11:21 UTC, divinecharlotte submitted a review, later dismissed

2024-11-12 13:27 UTC, musayann requested changes

2024-11-12 13:27 UTC, musayann commented on apps/drec-api/src/pods/reads/reads.controller.ts
> +  @UseGuards(AuthGuard(), PermissionGuard)
did we have to add this Auth guard here ?

2024-11-12 13:27 UTC, musayann commented on apps/drec-api/src/pods/reads/reads.controller.ts
> +  @Post('upload')
I would rename this path to something like `csv-upload`

2024-11-12 13:27 UTC, musayann commented on apps/drec-api/src/pods/reads/reads.controller.ts
> +    FileInterceptor('file', {
can't we move this logic into a DTO ?

2024-11-12 13:27 UTC, musayann commented on apps/drec-api/src/utils/csv-parser.ts
> +    parser.on('readable', () => {
I would suggest to have a csv parser into it's own helper function just so we can use it later in other areas

2024-11-12 13:27 UTC, musayann commented on apps/drec-api/src/pods/reads/reads.service.ts
> +  ): Promise<{ success: number; failed: Array<{ read: any; error: string }> }> {
this logic should be moved to the processor

2024-11-12 13:27 UTC, musayann commented on apps/drec-api/src/pods/reads/reads.service.ts
> +          timestamp: new Date(read.timestamp),
Shouldn't the timestamp come from the csv ?

2024-11-12 13:27 UTC, musayann commented on apps/drec-api/src/pods/reads/reads.service.ts
> +      unit: Unit.kWh,
the unit shouldn't be hardcoded

2024-11-12 13:27 UTC, musayann commented on apps/drec-api/src/pods/reads/reads.service.ts
> +        await this.validateAndStoreMeterRead(read);
I would suggest to trigger the usual logic for validating meter read from this service instead of bypassing it

2025-01-14 09:52 UTC, musayann requested changes

2025-01-14 09:52 UTC, musayann commented on apps/drec-api/migrations/1736414685134-create-file-processing-failed-reads-logs.ts
> +      CREATE TABLE "file_processing_failed_reads_logs" (
can we rename this to `file_processing_failed_logs` it would keep logs based on the type

2025-01-14 10:20 UTC, musayann requested changes

2025-01-14 10:20 UTC, musayann commented on apps/drec-api/migrations/1734364288388-create-file-processing-jobs-table.ts
> +    `);
Follow this data structure for the bulk upload entity
<img width="1214" alt="Screenshot 2025-01-14 at 12 19 31" src="https://github.com/user-attachments/assets/0613a158-5b69-4a4f-bfaa-5e499af1ad9b" />

2025-01-16 17:41 UTC, musayann requested changes

2025-01-16 17:41 UTC, musayann commented on apps/drec-api/migrations/1736414685134-create-bulk-upload-failed-logs.ts
> +        "errorDetails" json NOT NULL,
I would suggest to name this field to `details`

2025-01-16 17:41 UTC, musayann commented on apps/drec-api/src/pods/file/bulk-upload.dto.ts
> +
can we move these into `pods/bulk-upload`

2025-01-16 17:41 UTC, musayann commented on apps/drec-api/src/pods/file/bulk-upload.dto.ts
> +
anything named `bulk-upload`

2025-01-16 17:41 UTC, musayann commented on apps/drec-api/src/pods/file/bulk-upload.dto.ts
> +
The name of this DTO is misleading. I'm unsure if it's used to create a bulk upload or retrieve them. If it's used for retrieving the bulk-uploads I think it should be named differently

2025-01-16 17:41 UTC, musayann commented on apps/drec-api/src/pods/file/bulk-uploads.entity.ts
> +  failedLog: BulkUploadFailedLogEntity[];
it should be `failedLogs` since it's an array and the element can have more than 1 log

2025-01-16 17:41 UTC, musayann commented on apps/drec-api/src/pods/reads/reads.controller.ts
> +    this.logger.verbose('Handling meter read file upload');
We need to check if the user has access to manage the organization before uploading the file

2025-01-16 17:41 UTC, musayann commented on apps/drec-api/src/pods/reads/reads.controller.ts
> +    }),
Can we store this File interceptor in a reusable file just so we can reuse it on other endpoints. It shouldn't be stored in this file

2025-01-16 17:41 UTC, musayann commented on apps/drec-api/src/pods/reads/reads.controller.ts
> +    }
this logic needs to be replaced by the function `checkIfCanManage`

2025-01-16 17:41 UTC, musayann commented on apps/drec-api/src/pods/reads/reads.controller.ts
> +      } else {
this logic needs to be replaced by the function `checkIfCanManage`

2025-01-16 17:41 UTC, musayann commented on apps/drec-api/src/pods/reads/reads.controller.ts
> +      return this.internalReadsService.getAllCSVJobsForAdmin(
Let's use the same name of `BulkUpload` instead of `CSV`.

This should be something like `getAllBulkUploadJobs`

2025-01-16 17:41 UTC, musayann commented on apps/drec-api/src/pods/reads/reads.controller.ts
> +      return this.internalReadsService.getAllBulkUploads(
this should be `getOrganizationBullkUploadJobs`

2025-01-16 17:41 UTC, musayann commented on apps/drec-api/src/pods/reads/reads.controller.ts
> +      return this.internalReadsService.getAllCSVJobsForApiUser(
This should also be renamed

2025-01-16 17:41 UTC, musayann commented on apps/drec-api/src/pods/reads/reads.service.ts
> +  async getAllBulkUploads(
this function should be moved to `/pods/bulk-uploads/bulk-uploads.service.ts`

2025-01-16 17:41 UTC, musayann commented on apps/drec-api/src/pods/reads/reads.service.ts
> +    limit?: number,
this function should also have a parameter of type. For the type of bulk uploads

Bulk uploads in the future will be 
- meter reads
- devices
- reservations,...

2025-01-16 17:41 UTC, musayann commented on apps/drec-api/src/pods/reads/reads.service.ts
> +      where: { organizationId },
filter by bulk upload type as well

2025-01-16 17:41 UTC, musayann commented on apps/drec-api/src/pods/reads/reads.service.ts
> +    pageNumber?: number,
same here we need to have a type

2025-01-16 17:41 UTC, musayann commented on apps/drec-api/src/pods/reads/reads.service.ts
> +      order: {
we need to filter by type as well

2025-01-16 17:41 UTC, musayann commented on apps/drec-api/src/pods/reads/reads.service.ts
> +    pageNumber?: number,
We need a type and to filter by type

2025-01-16 17:41 UTC, musayann commented on apps/drec-api/src/pods/reads/reads.service.ts
> +  ): Promise<BulkUploadFailedLogEntity> {
this should also be in `/pods/bulk-uploads/bulk-uploads.service.ts`

2025-01-16 17:41 UTC, musayann commented on apps/drec-api/src/pods/reads/reads.service.ts
> +        destination: '',
separate the process of saving the file and creating a bulk upload from the queing of the meter reads

2025-01-16 17:41 UTC, musayann commented on apps/drec-api/src/pods/reads/reads.service.ts
> +
in this function everything above this point will go into the bulk-upload service in an a function to create a bulk upload

2025-01-16 17:41 UTC, musayann commented on apps/drec-api/src/pods/reads/reads.service.ts
> +
the meter read type will come as parameter

2025-01-16 17:41 UTC, musayann commented on apps/drec-api/src/pods/reads/reads.service.ts
> +        status: BulkUploadStatus.InProgress,
the status here should be `Added`

2025-01-16 17:41 UTC, musayann commented on apps/drec-api/src/pods/reads/reads.service.ts
> +        userId: user.id,
the job scheduling will stay in this function

2025-01-16 17:41 UTC, musayann commented on apps/drec-api/src/pods/reads/reads.service.ts
> +      await this.bulkUploadRepository.update(
this should not be here. Because we will throw the error directly to the user. Since the job hasn't started

2025-01-16 17:41 UTC, musayann commented on apps/drec-api/src/pods/reads/reads.controller.ts
> +  ): Promise<BulkUploadDTO | undefined> {
This endpoint will go into `pods/bulk-uploads/bulk-uploads.controller.ts`

2025-01-16 17:41 UTC, musayann commented on apps/drec-api/src/pods/reads/reads.controller.ts
> +  ): Promise<BulkUploadDTO | undefined> {
this endpoint will just need an id and will not need a type or similar. It should be usable across all bulk upload types

2025-01-16 17:47 UTC, musayann requested changes

2025-01-16 17:47 UTC, musayann commented on apps/drec-api/src/pods/reads/reads.controller.ts
> +  @Get('/get-csv-jobs')
this endpoint would just be `@Get()` and it will be in `pods/bulk-uploads/bulk-uploads.controller.ts`

2025-01-16 17:53 UTC, musayann requested changes

2025-01-16 17:53 UTC, musayann commented on apps/drec-api/src/pods/reads/reads.controller.ts
> +      properties: {
This endpoint should be renamed `@Post()` and moved into `/pods/bulk-upload/bulk-upload.controller.ts`

2025-01-16 17:53 UTC, musayann commented on apps/drec-api/src/pods/reads/reads.controller.ts
> +  @ApiSecurity('bearer')
We should only allow access to this endpoint if the user has the access to manage the organization and if the organization is a `Developer`

2025-01-16 17:53 UTC, musayann commented on apps/drec-api/src/pods/reads/reads.service.ts
> +      const job = await this.readsQueue.add('meter-reads-csv', {
The queue should be `meter-reads-bulk-upload`. We need to replace the `csv` keyword with `bulk-upload`

2025-01-16 17:53 UTC, musayann commented on apps/drec-api/src/pods/reads/reads.service.ts
> +      });
We will trigger the job based on the type of bulk upload

2025-01-22 10:13 UTC, musayann approved these changes

2025-01-22 10:13 UTC, merged