Ft/user custom validation
d-rec/drec-origin pull request #442
Opened 2024-11-01 09:52 UTC by Kingcedru

### Description

We want to create a custom validation to check if a user can add data for the organizationId.

### Issue ticket #438 

### Checklist before requesting a review

- [ ] A new validation is created and applied to the reads endpoints
- [ ] The validation works as before and doesn't break anything
- [ ] When applying the validation to an endpoint make sure to remove any code that was used to do a similar check
- [ ] I have performed a self-review of my code
- [ ] No existing features have been broken without good reason.
- [ ] The code style guidelines have been followed
- [ ] Documentation has been updated to reflect my changes.

2024-11-01 15:44 UTC, Kingcedru commented
I'm trying to test the validation and get the `TypeError: Cannot read properties of undefined (reading 'findOne')` error. I tried to console log the organizationId and try other ways but still I wasn't able to get it. I don't understand why I continue getting that error.

2024-11-15 14:11 UTC, divinecharlotte requested changes
I left some comments there
- Consider checking the end point of getting devices it's kinda not working as expected

2024-11-15 14:11 UTC, divinecharlotte commented on apps/drec-api/package.json
> +    "sql-parser": "~0.5.0",
- why did you affect this file curious question 😃 ???

2024-11-18 06:44 UTC, divinecharlotte submitted a review, later dismissed
looks good now

2024-11-18 12:52 UTC, musayann requested changes

2024-11-18 12:52 UTC, musayann commented on apps/drec-api/src/guards/organization-access.guard.ts
> +      } else if (
we don't need an else if since the first statement has a throw. Just use an independent `if`

2024-11-18 12:52 UTC, musayann commented on apps/drec-api/src/guards/organization-access.guard.ts
> +    try {
I don't think this try-and-catch is useful here. It doesn't add any value

2024-11-18 12:52 UTC, musayann commented on apps/drec-api/src/guards/organization-access.guard.ts
> +export class OrganizationAccessGuard implements CanActivate {
can we rename this to `OrganizationManageGuard`

2024-11-18 12:52 UTC, musayann commented on apps/drec-api/package.json
> +}
I don't think these changes are needed here

2024-11-21 10:44 UTC, musayann requested changes

2024-11-21 10:44 UTC, musayann commented on apps/drec-api/src/guards/organization-access.guard.ts
> +    return true;
Can we convert the following block into a reusable function with just two parameters the `user` and `organizationId`

```ts
if (!user || !organizationId) {
      throw new UnauthorizedException('User or organizationId not provided');
    }

    const senderOrg = await this.organizationService.findOne(organizationId);
    const orgUser = await this.userService.findByEmail(senderOrg.orgEmail);

    if (user.id !== organizationId && user.role !== Role.ApiUser) {
      this.logger.error(`Organization mismatch`);
      throw new ConflictException(
        "Organization in measurement is not same as user's organization",
      );
    }

    if (
      user.role === Role.ApiUser &&
      senderOrg.api_user_id !== user.api_user_id
    ) {
      this.logger.error(`User lacks organization access`);
      throw new ConflictException(
        `Organization ${senderOrg.name} not accessible to user`,
      );
    }
    if (user.role === Role.ApiUser && orgUser.role !== Role.OrganizationAdmin) {
      this.logger.error(`Unauthorized`);
      throw new UnauthorizedException(`Unauthorized`);
    }

    return true;
    ```

2024-11-26 13:22 UTC, musayann reviewed
remove the `package-lock.json`

2024-11-27 13:47 UTC, musayann approved these changes

2024-11-27 13:53 UTC, merged