Ft/timestamp validation class
d-rec/drec-origin pull request #446
Opened 2024-11-12 13:09 UTC by divinecharlotte

### Describe your changes

[REPLACE WITH DESCRIPTION]

### Issue ticket number and link

- #[REPLACE_WITH_ISSUE_NUMBER]

### Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] No existing features have been broken without good reason.
- [ ] The code style guideline have been followed
- [ ] Documentation has been updated to reflect your changes.

2024-11-13 10:23 UTC, Kingcedru requested changes

2024-11-13 10:23 UTC, Kingcedru commented on apps/drec-api/src/pods/reads/reads.controller.ts
> +              milliSeondsToAddSentInRequest +
It seem like we don't need this codes.

2024-11-14 07:50 UTC, Kingcedru submitted a review, later dismissed

2024-11-15 08:20 UTC, musayann requested changes

2024-11-15 08:20 UTC, musayann commented on apps/drec-api/src/validations/timestamp.ts
> +      const endTimestamp = ele.endtimestamp;
We should validate the timestamp individually

2024-11-18 12:56 UTC, musayann requested changes

2024-11-18 12:56 UTC, musayann commented on apps/drec-api/src/validations/timestamp.ts
> +      const startTimestamp = ele.starttimestamp;
This wouldn't work. Here were are assuming that we are validating an object which contains both the `startTimestmap` and `endTimestamp` which is not the case

2024-11-18 13:34 UTC, divinecharlotte commented on apps/drec-api/src/validations/timestamp.ts
> +      const startTimestamp = ele.starttimestamp;
@musayann I did so because there will be a time when we will validate both, mainly `history read`, and when it's only one of them validate it alone. So, I am not getting what you mean here. I am probably missing something out. May you provide more clarification?

2024-11-22 08:10 UTC, musayann requested changes

2024-11-22 08:10 UTC, musayann commented on apps/drec-api/src/pods/reads/reads.controller.ts
> -                  }
this part is not implemented. We should have a transformer for it

2024-11-29 07:52 UTC, Kingcedru approved these changes, later dismissed

2024-12-10 17:31 UTC, musayann submitted a review, later dismissed

2024-12-10 17:37 UTC, musayann approved these changes, later dismissed

2024-12-11 20:09 UTC, musayann approved these changes

2024-12-11 20:10 UTC, merged