refactor: certificate log
d-rec/drec-origin pull request #452
Opened 2024-11-20 13:14 UTC by musayann

### Describe your changes

[REPLACE WITH DESCRIPTION]

### Issue ticket number and link

- #[REPLACE_WITH_ISSUE_NUMBER]

### Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] No existing features have been broken without good reason.
- [ ] The code style guideline have been followed
- [ ] Documentation has been updated to reflect your changes.

2024-11-21 12:58 UTC, Kingcedru submitted a review, later dismissed

2024-11-22 08:50 UTC, divinecharlotte approved these changes

2024-11-22 08:55 UTC, divinecharlotte requested changes
Hello @musayann ,
This PR has some conflicts

2024-11-26 12:10 UTC, divinecharlotte approved these changes

2024-11-27 09:44 UTC, Kingcedru approved these changes

2024-11-27 13:43 UTC, merged