Refactor: moving the create validation to the DTO
d-rec/drec-origin pull request #458
Opened 2024-11-25 09:54 UTC by Kingcedru

### Describe your changes

Updating the validation logic in the device controller and moving them into the DTO

### Issue ticket number and link

- #457 

### Checklist before requesting a review

- [ ] The validations are working normally.
- [ ] I have performed a self-review of my code
- [ ] No existing features have been broken without good reason.
- [ ] The code style guidelines have been followed

2024-11-28 07:27 UTC, Kingcedru commented
Solve the conflicts

2024-11-29 09:58 UTC, divinecharlotte requested changes
- Kindly check each validation independently to see if it's implementing what it was intended to do because currently some breaking the app below i highlighted one that is behaving that way

2024-11-29 09:58 UTC, divinecharlotte commented on apps/drec-api/src/pods/device/dto/new-device.dto.ts
> +  @IsNotEmpty({ message: 'externalId should not be empty' })
- This validation is not working at all kindly check it out and fix it to avoid this internal server error `[Nest] 34674  - 11/29/2024, 11:41:24 AM   ERROR [ExceptionsHandler] value?.trim is not a function
TypeError: value?.trim is not a function`

2024-12-04 09:04 UTC, divinecharlotte requested changes
Hello @Kingcedru  I left some comments concerning the new device validation you may check them out and Implement them  and remember when doing so implement them to the update device validations as well

2024-12-04 09:04 UTC, divinecharlotte commented on apps/drec-api/src/pods/device/device.controller.ts
> +    console.log(deviceToUpdate);
- kindly remove this console to make your code clean 😺

2024-12-04 09:04 UTC, divinecharlotte commented on apps/drec-api/src/pods/device/dto/new-device.dto.ts
>    IsNotEmpty,
I got confused a bit, how do these validations work together ❓

2024-12-04 09:04 UTC, divinecharlotte commented on apps/drec-api/src/pods/device/dto/new-device.dto.ts
> +  @IsNotEmpty({ message: 'externalId should not be empty' })
please check this out its the Trim function is still breaking the app wit this error ` value.trim is not a function
TypeError: value.trim is not a function`

2024-12-04 09:04 UTC, divinecharlotte commented on apps/drec-api/src/pods/device/device.controller.ts
> -    }
- This part was removed but its implementation in the trim function is not working please fix that

2024-12-04 09:04 UTC, divinecharlotte commented on apps/drec-api/src/validations/commissioning-date.validator.ts
> +          if (!currentValue) return 'Commissioning date is required';
- How about moving this validation in the DTO as well using `IsNotEmpty()` decorator  this will also reduce number of lines  used to check this

2024-12-04 09:04 UTC, divinecharlotte commented on apps/drec-api/src/validations/commissioning-date.validator.ts
> +          const currentValue = args.value;
- Overall this validator is not doing anything concerning the valid format of the commission date as it was being done here    
```
if (!isValidUTCDateFormat(deviceToRegister.commissioningDate)) {
      this.logger.error(
        `Invalid commissioning date, valid format is  YYYY-MM-DDThh:mm:ss.millisecondsZ example 2022-10-18T11:35:27.640Z`,
      );
      throw new ConflictException({
        success: false,
        message:
          ' Invalid commissioning date, valid format is  YYYY-MM-DDThh:mm:ss.millisecondsZ example 2022-10-18T11:35:27.640Z ',
      });
    }
```

And I think here we will need to use the time stamp validator because it validates any kind of timestamp in such a format timestamp validator is implemented in ticket #444 and all the transformation is done there 😺

2024-12-04 09:04 UTC, divinecharlotte commented on apps/drec-api/src/pods/device/device.controller.ts
> -    }
- This validation is removed but its implementation in the DTO is not working kindly check that out

2024-12-04 09:04 UTC, divinecharlotte commented on apps/drec-api/src/pods/device/dto/new-device.dto.ts
> +  @Transform((value, obj) => parseFloat(obj.capacity))
- this validation is not working because if I  add capacity with 0 value its still work yet it was supposed to be caught as invalid value

2024-12-10 07:35 UTC, divinecharlotte approved these changes, later dismissed

2024-12-10 18:07 UTC, musayann requested changes

2024-12-10 18:07 UTC, musayann commented on apps/drec-api/src/pods/device/device.controller.ts
> +    console.log(org);
can you remove this console.log.

Can you check if this PR works as expected. (we can register devices, add meter reads and certificates can be generated

2024-12-10 18:07 UTC, musayann commented on apps/drec-api/src/pods/device/device.controller.ts
> +      console.log(user.organizationId);
Let's remove all the `console.log`

2024-12-10 18:07 UTC, musayann commented on apps/drec-api/src/transformers/trim-string.ts
> +  applyDecorators(
this should be in `string.ts`

2024-12-10 18:07 UTC, musayann commented on apps/drec-api/src/pods/device/dto/update-device.dto.ts
> +  @Transform((value, obj) => obj.countryCode.toUpperCase())
This should be used ordered last. it should also be a reusable transformer.

2024-12-10 18:07 UTC, musayann commented on apps/drec-api/src/pods/device/dto/update-device.dto.ts
> +      'Invalid countryCode, some of the valid country codes are "GBR" - "United Kingdom of Great Britain and Northern Ireland",  "CAN" - "Canada"  "IND" - "India", "DEU"-  "Germany"',
here we are just checking that length is 3 but we are not checking if the code is right. We removed the validation that were used to check if the provided country code matches the existing country codes.

We can use the following to validate

```ts
@IsIn(countryCodesArray)
```

2024-12-10 18:07 UTC, musayann commented on apps/drec-api/src/pods/device/dto/update-device.dto.ts
> +  @IsValidCommissioningDate()
this validation should be a comparison to check if a date is less than today. We shouldn't name this `IsValidCommissioningDate` since this is normal check if a date is less or equal to a date. I would suggest to check first if that validation doesn't exist already in class-validator.

class validator should support something like

```ts
    @Transform( ({ value }) => new Date(value))
    @IsDate()
    @MaxDate(new Date())
    myDate: Date;
```

2024-12-13 11:42 UTC, musayann requested changes

2024-12-13 11:42 UTC, musayann commented on apps/drec-api/src/pods/device/dto/update-device.dto.ts
> +  @IsNotEmpty({ message: 'externalId should not be empty' })
We should not use `IsNotEmpty` with optional

2024-12-13 14:29 UTC, musayann requested changes

2024-12-13 14:29 UTC, musayann commented on apps/drec-api/src/pods/device/dto/update-device.dto.ts
> +  @Matches(/^[A-Z]{3}$/, {
I think this match doesn't serve anything anymore

2024-12-13 14:29 UTC, musayann commented on apps/drec-api/src/pods/device/dto/update-device.dto.ts
> +  @Min(1, {
I think this mean capacity is not correct. You are saying that it should be greater than 0. but between 0 and 1 there are other values

2024-12-13 14:29 UTC, musayann commented on apps/drec-api/src/pods/device/dto/update-device.dto.ts
> +  @MaxDate(new Date(), {
did you check if this implementation works ?

2024-12-13 14:29 UTC, musayann commented on apps/drec-api/src/pods/device/dto/update-device.dto.ts
>    commissioningDate: string;
the type here should be Date not string. I don't think the transformer will return a string

2024-12-13 14:29 UTC, musayann commented on apps/drec-api/src/pods/device/dto/new-device.dto.ts
> +  @ValidateIf((o) => o.version === null || o.version === undefined)
not sure what this statement stands for

2024-12-16 09:37 UTC, musayann requested changes

2024-12-16 09:37 UTC, musayann commented on apps/drec-api/src/pods/device/dto/new-device.dto.ts
>    address: string;
is this required ?

2024-12-16 09:37 UTC, musayann commented on apps/drec-api/src/pods/device/dto/new-device.dto.ts
> -  // @IsOptional()
is this one required ?

2024-12-16 09:37 UTC, musayann commented on apps/drec-api/src/pods/device/dto/new-device.dto.ts
> -  // @IsOptional()
we need to check if these are now required just so we can require them as not empty

2024-12-16 09:37 UTC, musayann commented on apps/drec-api/src/pods/device/dto/update-device.dto.ts
> -  @IsOptional()
is this now required since you removed the `@IsOptional` decorator ?

2024-12-16 09:37 UTC, musayann commented on apps/drec-api/src/pods/device/device.controller.ts
> +          (ele) => ele.countryCode === deviceToUpdate.countryCode,
do we need to rerun this validation since this would have been done in the DTO

2025-01-20 13:54 UTC, musayann requested changes

2025-01-20 13:54 UTC, musayann commented on apps/drec-api/src/index.ts
> +    new ValidationPipe({ forbidUnknownValues: false, transform: true }),
didn't the transform introduce issues on other endpoints ?

2025-01-20 13:54 UTC, musayann commented on apps/drec-api/src/transformers/uppercase.ts
> +export const ToUpperCase = (): PropertyDecorator =>
I would suggest to name the decorator `UpperCase` only

2025-01-20 13:54 UTC, musayann commented on apps/drec-api/src/pods/device/device.controller.ts
> +    if (user.role === Role.Admin) {
this logic to check if a user has access to an organization is already implemented in the function of `canManage`

2025-01-22 12:41 UTC, musayann submitted a review, later dismissed

2025-01-22 13:28 UTC, musayann approved these changes

2025-01-22 13:28 UTC, merged