Mofeat:ve validations done in the user controllers into DTO
d-rec/drec-origin pull request #459
Opened 2024-11-25 12:57 UTC by divinecharlotte

### Move validations done in the user controllers into DTO
Update user controller and move the validation logic to the DTO

### Issue ticket #456 and [link](https://github.com/orgs/d-rec/projects/2/views/1?pane=issue&itemId=88479106&issue=d-rec%7Cdrec-origin%7C456)

### Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] No existing features have been broken without good reason.
- [x] The code style guideline have been followed
- [x] Documentation has been updated to reflect your changes.

2024-11-28 07:46 UTC, Kingcedru requested changes
Check all the validation and solve the conflicts

2024-11-28 07:46 UTC, Kingcedru commented on apps/drec-api/src/pods/user/user.controller.ts
> -    }
This validation is not done because if I send an empty string with space inside it I don't get any error and the response becomes successful.
**example:**
`{
  "firstName": "babous",
  "lastName": "cedrus",
  "email": "babouce@gmail.com",
  "organizationType": "Buyer",
  "password": "King@123",
  "confirmPassword": "King@123",
  "orgName": " ",
  "orgAddress": "KN150"
}`

2024-11-28 07:46 UTC, Kingcedru commented on apps/drec-api/src/pods/user/user.controller.ts
> -    }
This validation is not implemented because when I send an organizationType with `buyer` I get a forbidden error.

Example
`{
  "firstName": "babous",
  "lastName": "cedrus",
  "email": "babouce@gmail.com",
  "organizationType": "buyer",
  "password": "King@123",
  "confirmPassword": "King@123",
  "orgName": "BC group",
  "orgAddress": "KN150"
}
`
**response**
`{
  "statusCode": 403,
  "message": "Forbidden resource",
  "error": "Forbidden"
}`

2024-11-28 13:00 UTC, Kingcedru approved these changes, later dismissed

2024-12-10 17:19 UTC, musayann requested changes

2024-12-10 17:19 UTC, musayann commented on apps/drec-api/src/pods/user/user.controller.ts
> -    ) {
here you have removed the validation to check if the organization type matches certain values and this validation wasn't added to the DTO

2024-12-11 13:50 UTC, musayann approved these changes

2024-12-11 13:51 UTC, merged