feat: sentry integration
d-rec/drec-origin pull request #470
Opened 2024-12-03 07:33 UTC by Kingcedru

### Describe your changes

[REPLACE WITH DESCRIPTION]

### Issue ticket number and link

- #[REPLACE_WITH_ISSUE_NUMBER]

### Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] No existing features have been broken without good reason.
- [ ] The code style guideline have been followed
- [ ] Documentation has been updated to reflect your changes.

2024-12-09 15:54 UTC, divinecharlotte approved these changes, later dismissed

2024-12-10 17:49 UTC, musayann requested changes

2024-12-10 17:49 UTC, musayann commented on apps/drec-api/src/index.ts
> +import './instrument';
shouldn't we call this `sentry` why instrument ?

2024-12-10 17:49 UTC, musayann commented on apps/drec-api/src/instrument.ts
> +    environment: process.env.NODE_ENV,
We should separate the `environment` here with `process.env.NODE_ENV`.

`process.env.NODE_ENV` is primarily used to indicate if we are running in local or built (production) mode.

We should have an env Variable that we will assign to the `environment` property that will be called `SENTRY_ENV`

We should disable reporting if `process.env.NODE_ENV` is not equal to `production`

2024-12-11 16:46 UTC, merged