Feat: rename variables camel case
d-rec/drec-origin pull request #471
Opened 2024-12-04 07:53 UTC by Kingcedru

### Describe your changes

[REPLACE WITH DESCRIPTION]

### Issue ticket number and link

- #[REPLACE_WITH_ISSUE_NUMBER]

### Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] No existing features have been broken without good reason.
- [ ] The code style guideline have been followed
- [ ] Documentation has been updated to reflect your changes.

2024-12-06 13:25 UTC, musayann requested changes

2024-12-06 13:25 UTC, musayann commented on apps/drec-api/src/pods/access-control-layer-module-service/access-control-layer-module-service.spec.ts
> +  let PermissionValue: DecimalPermissionValue;
variables should be in camelCase no ?

2024-12-06 13:25 UTC, musayann commented on apps/drec-api/src/pods/certificate-log/certificate-log.service.spec.ts
> +      const getNewReservationInfo = { deviceGroups: [] };
`get` should be used on functions only not on variables

2024-12-06 13:25 UTC, musayann commented on apps/drec-api/src/pods/certificate-log/certificate-log.service.spec.ts
> +      const getNewReservationInfo = { deviceGroups: [] };
remove the `new` keyword as well

2024-12-10 16:16 UTC, musayann requested changes

2024-12-10 16:16 UTC, musayann commented on apps/drec-api/src/pods/access-control-layer-module-service/common/permissionBitposition.ts
> +    const permission: any = [];
this should be named `permissions`

2024-12-10 16:16 UTC, musayann commented on apps/drec-api/src/pods/admin/admin.controller.ts
> +    const manyOtherUserInOrg =
I would suggest a name like `otherOrgUsers`

2024-12-10 16:16 UTC, musayann commented on apps/drec-api/src/pods/certificate-log/certificate-log.service.spec.ts
> +      const reservationInforDeveloperBsiseSpy = jest
this variable name looks strange

2024-12-10 16:16 UTC, musayann commented on apps/drec-api/src/pods/certificate-log/certificate-log.service.spec.ts
> +      const getOldReservationInfo = { deviceGroups: [] };
shouldn't this be name `oldReservationInfo`

2024-12-10 16:16 UTC, musayann commented on apps/drec-api/src/pods/certificate-log/certificate-log.service.spec.ts
> +      const getNewReservationInfo = {
and this to `reservationInfo`

2024-12-11 16:34 UTC, musayann requested changes

2024-12-11 16:34 UTC, musayann commented on apps/drec-api/src/pods/device/device.controller.ts
> +        fitleRop = {
what does `fitleRop` I think there is a typo here

2024-12-11 16:34 UTC, musayann commented on apps/drec-api/src/pods/email-confirmation/email-confirmation.service.ts
> +    const allemialConfirm = await this.get(userId);
what does `allemial` mean ? I think they meant `allEmailConfirmations`. I would suggest to just use `confirmation`

2024-12-11 16:34 UTC, musayann commented on apps/drec-api/src/pods/invitation/invitation.service.spec.ts
> +      const inviteeFindOneSpy = jest
let's rename it to `inviteFindOneSpy`

2024-12-11 16:34 UTC, musayann commented on apps/drec-api/src/pods/permission/permission.service.spec.ts
> +  let ACLPermissionService: AccessControlLayerModuleServiceService;
this should be `aclPermissionService`

2024-12-11 16:34 UTC, musayann commented on apps/drec-api/src/pods/permission/permission.service.ts
> +      const ACLPermission = new ACLModulePermissions({
This should `aclPermissionService`

2024-12-11 16:34 UTC, musayann commented on apps/drec-api/src/pods/permission/permission.service.ts
> +    const isPermission =
This should `permissions`

2024-12-11 16:34 UTC, musayann commented on apps/drec-api/src/pods/permission/permission.service.ts
> +    const ACLPermission = await this.repository.find({
This should `aclPermission`

2024-12-11 16:34 UTC, musayann commented on apps/drec-api/src/pods/permission/permission.service.ts
> +    const permissionBoolean = await this.checkForExistingmodulepermission(
This should be `hasPermission`

2024-12-11 16:34 UTC, musayann commented on apps/drec-api/src/pods/permission/permission.service.ts
> +    const apiUserpermission = await this.userService.getApiuser(
This should `apiUserPermission`

2024-12-11 16:34 UTC, musayann commented on apps/drec-api/src/pods/sdgbenefit/sdgbenefit.controller.ts
> +    return SDGBCode.map((sdgb) => plainToClass(SDGBCodeNameDTO, sdgb));
This should be `sdgBenefitCode`

2024-12-11 16:34 UTC, musayann commented on apps/drec-api/src/pods/device-group/device-group.service.ts
> +              const newSdg = filterDto.SDGBenefits.toString();
this should be `newSDG`

2024-12-11 16:34 UTC, musayann commented on apps/drec-api/src/pods/device-group/device-group.service.ts
> +              const newSdg = filterDto.SDGBenefits.toString();
same here

2024-12-11 16:34 UTC, musayann commented on apps/drec-api/src/pods/device-group/device-group.service.ts
> +    const groupedDataSql = await queryBuilder
this should be `groupedDataSQL`

2024-12-11 20:27 UTC, musayann submitted a review, later dismissed

2024-12-12 15:19 UTC, divinecharlotte approved these changes

2024-12-12 15:31 UTC, merged