feat:Rename class names and types to PascalCase
d-rec/drec-origin pull request #472
Opened 2024-12-06 10:13 UTC by divinecharlotte

### Renaming class names and types to PascalCase
We wanted to rename all the class names, typescript types and enums used in the project to PascalCase

### Issue ticket #469 and[ link](https://github.com/orgs/d-rec/projects/2/views/1?pane=issue&itemId=89125573&issue=d-rec%7Cdrec-origin%7C469)

### What I did

- Renamed all class names, typescript types, and enums used in the project to PascalCase
- Didn't rename anything else. Functions, variables, constants, and file names are out of scope for this ticket
- Made sure that the test run and nothing breaks

### Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] No existing features have been broken without good reason.
- [x] The code style guideline have been followed
- [x] Documentation has been updated to reflect your changes.

2024-12-07 15:00 UTC, Kingcedru requested changes

2024-12-07 15:00 UTC, Kingcedru commented on apps/drec-api/src/pods/certificate-log/certificate-log.service.ts
> +      | CertificateWithPerDevicelog[];
`log` is not starting with a capital letter

2024-12-09 17:00 UTC, Kingcedru submitted a review, later dismissed
Good

2024-12-10 17:41 UTC, musayann requested changes

2024-12-10 17:41 UTC, musayann commented on apps/drec-api/src/pods/sdgbenefit/sdgbenefit.module.ts
> +export class SDGbenefitModule {}
This should be `SDGBenefitModule`

2024-12-11 13:54 UTC, musayann requested changes

2024-12-11 13:54 UTC, musayann commented on apps/drec-api/src/drec.module.ts
> +import { SDGbenefitModule } from './pods/sdgbenefit/sdgbenefit.module';
This should also be `SDGBenefitModule`

2024-12-11 15:51 UTC, musayann approved these changes

2024-12-11 15:52 UTC, merged