feat:Rename function names to camelCase
d-rec/drec-origin pull request #473
Opened 2024-12-09 10:35 UTC by divinecharlotte

### Describe your changes

[REPLACE WITH DESCRIPTION]

### Issue ticket number and link

- #[REPLACE_WITH_ISSUE_NUMBER]

### Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] No existing features have been broken without good reason.
- [ ] The code style guideline have been followed
- [ ] Documentation has been updated to reflect your changes.

2024-12-11 12:01 UTC, Kingcedru requested changes

2024-12-11 12:01 UTC, Kingcedru commented on apps/drec-api/src/drec.module.ts
> +const queueingModule = () => {
I would suggest `queueModule` as the function name.

2024-12-11 12:01 UTC, Kingcedru commented on apps/drec-api/src/pods/certificate-log/certificate-log.service.spec.ts
> +            getOldReservationInfOrDeveloperBsise: jest.fn(),
The name of this function is confusing.

2024-12-11 12:01 UTC, Kingcedru commented on apps/drec-api/src/pods/certificate-log/certificate-log.service.ts
> +  async getLastCertifiedDevicelogBygroupId(
groupId is starting with a small letter.

2024-12-11 12:01 UTC, Kingcedru commented on apps/drec-api/src/pods/device-group/buyer-reservation.controller.ts
> +  public async endResavation(
You can change the spelling of  reservation.

2024-12-11 12:01 UTC, Kingcedru commented on apps/drec-api/src/pods/reads/reads.controller.ts
> +  public async newstoreReadaddByAdmin(
Add is starting in a small letter

2024-12-11 12:01 UTC, Kingcedru commented on apps/drec-api/src/pods/user/oauth_client.service.ts
> +  async findOneByclientId(
client is starting with a small letter

2024-12-12 09:20 UTC, Kingcedru requested changes

2024-12-12 09:20 UTC, Kingcedru commented on apps/drec-api/src/pods/device-group/buyer-reservation.controller.ts
> +  async getDevcieGroupLog(
There is a typo on this function name. `Devcie`

2024-12-12 09:20 UTC, Kingcedru commented on apps/drec-api/src/pods/device-group/device-group.service.ts
> +  async getCurrentInformationofDevicesInReservation(
`of` is written with a small letter.

2024-12-12 09:20 UTC, Kingcedru commented on apps/drec-api/src/pods/device/device.service.ts
> +  async getCertifiedDeviceDateRangeBygroupId(
`group` is starting with a small letter.

2024-12-12 09:20 UTC, Kingcedru commented on apps/drec-api/src/pods/user/oauth_client.service.ts
> +  async findOneByuserId(
`user` starts with a small letter.

2024-12-12 09:20 UTC, Kingcedru commented on apps/drec-api/src/pods/reads/reads.controller.ts
> +  public async newstoreReadAddByAdmin(
`store` starts with a small letter. You can change it.

2024-12-12 10:18 UTC, Kingcedru approved these changes, later dismissed

2024-12-12 16:03 UTC, musayann requested changes

2024-12-12 16:03 UTC, musayann commented on apps/drec-api/src/pods/device/device.controller.ts
> +  async certifiedLogDateRang(
this should be `certifiedLogDateRange`

2024-12-12 16:03 UTC, musayann commented on apps/drec-api/src/pods/file/api-multi-file.decorator.ts
> +export const APIFile =
isn't this a function ?

2024-12-12 16:03 UTC, musayann commented on apps/drec-api/src/pods/issuer/issuer.service.spec.ts
>              EndReservationGroup: jest.fn(),
this should be in camel case right ?

2024-12-12 16:03 UTC, musayann commented on apps/drec-api/src/pods/permission/permission.controller.ts
> +    return this.PermissionService.permissionVeify(api_user_id, moduleData);
the function name should be `verify` since we already in the permission context

2024-12-12 16:03 UTC, musayann commented on apps/drec-api/src/pods/permission/permission.controller.ts
> +    return this.PermissionService.permisssionRequest(moduleData, loggedUser);
the function name should be `request` since we already in the permission context

2024-12-12 16:03 UTC, musayann commented on apps/drec-api/src/pods/permission/permission.controller.ts
> +  public async APIUserModuleRequest(
function should always be in camelCase. in this case, it will be `apiUserModuleRequest`

2024-12-12 16:03 UTC, musayann commented on apps/drec-api/src/pods/reads/reads.service.ts
> +    const numberOfHistReads = await this.getNumberOfHistReads(
name this one `getNumberOfHistoryReads`

2024-12-12 16:03 UTC, musayann commented on apps/drec-api/src/pods/reads/reads.service.ts
> +    numberOfOngReads = await this.getNumberOfOngReads(
name this one `getNumberOfOngoingReads`

2024-12-13 10:47 UTC, musayann commented on apps/drec-api/src/pods/certificate-log/certificate-log.service.ts
> +  async getDeveloperFindCertifiedReservations(
can you rename this function to `getDeveloperCertifiedReservations`

2024-12-13 11:39 UTC, musayann approved these changes

2024-12-13 11:40 UTC, merged